secret_key_base: <%= ENV['secret_key_base'] %>
google_maps_api_key: <%= ENV['google_maps_api_key'] %>
mailchimp_api_key: <%= ENV['mailchimp_api_key'] %>
mailchimp_audience_id: <%= ENV['mailchimp_audience_id'] %>
smtp_user_name: <%= ENV['smtp_user_name'] %>
smtp_password: <%= ENV['smtp_password'] %>
smtp_domain: <%= ENV['smtp_domain'] %>
smtp_address: <%= ENV['smtp_address'] %>
smtp_port: <%= ENV['smtp_port'] %>